'Domain\Entities\Book':
    type: entity
    table: 'book'
    repositoryClass: Infrastructure\Persistence\Doctrine\Repositories\BooksRepository
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: 'book_seq'
                allocationSize: 1
                initialValue: 1
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        author:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
