version: '3'
services:

    db: 
        container_name: db
        build: ./environment/postgres
        env_file:
            - ".env"
        restart: always
        volumes:
            - ./environment/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: home_crm
            POSTGRES_PASSWORD: home_crm
            POSTGRES_DB: home_crm
        ports:
            - "5432:5432"

#     node:
#         container_name: node_rtn
#         build: ./node
#        env_file:
#            - ".env"
# #        user: "${USER}:${GROUP}"
#         working_dir: /home/node/api
#         environment:
#           - NODE_ENV=development
#         volumes:
#           - ../web/api:/home/node/api
#           - ./logs/node:/root/.npm/_logs
# #        expose:
# #          - "8081"
#         entrypoint: "tail -f /home/node/api/readme.md"

    redis: 
        container_name: redis
#        user: "${USER}:${GROUP}"
        build: ./environment/redis
        env_file:
            - ".env"
        restart: always
        volumes:
            - ./environment/redis/data:/data
            - ./environment/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"

    php_fpm:
        container_name: php_fpm
#        user: "${USER}:${GROUP}"
        build: ./environment/php-fpm
        env_file:
            - ".env"
        volumes:
            - ./:/var/www/html
            - ./environment/logs/node:/root/.npm/_logs
#            - ./environment/php-fpm/.composer/cache:/.composer/cache
        ports:
            - "9000:9000"
        links:
            - db
            - redis

    web_crm_auth:
        container_name: web_crm_auth
#        user: "${USER}:${GROUP}"
        build: ./environment/nginx
        env_file:
            - ".env"
        volumes:
            - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./environment/nginx/app.auth.vhost:/etc/nginx/conf.d/app.vhost
            #DESCOMENTAR CASO QUEIRA CUSTOMIZAR O OPCACHE DO PHP
            #- ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./environment/logs/nginx:/var/log/nginx
            - ../:/var/www/html
        ports:
            - "8080:80"
            - "4430:443"
        links:
            - php_fpm

    web_crm_books:
        container_name: web_crm_books
#        user: "${USER}:${GROUP}"
        build: ./environment/nginx
        env_file:
            - ".env"
        volumes:
            - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./environment/nginx/app.books.vhost:/etc/nginx/conf.d/app.vhost
            #DESCOMENTAR CASO QUEIRA CUSTOMIZAR O OPCACHE DO PHP
            #- ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./environment/logs/nginx:/var/log/nginx
            - ../:/var/www/html
        ports:
            - "8081:80"
            - "4431:443"
        links:
            - php_fpm

    pgadmin:
        container_name: pgadmin
        build: ./environment/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: db@madeiramadeira.com.br
            PGADMIN_DEFAULT_PASSWORD: madeira@1234
#            MAIL_SERVER: localhost
#            MAIL_PORT: 25
#            MAIL_USE_SSL: False
#            MAIL_USE_TLS: False
#            MAIL_USERNAME: None
#            MAIL_PASSWORD: None
        ports:
            - "5050:80"
        links:
            - db